'use strict';
var json;
/**
 * @ngdoc function
 * @name surveyTreeModuleApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the surveyTreeModuleApp
 */
angular.module('surveyTreeModuleApp')
  .controller('MainCtrl', function ($scope, $rootScope, $timeout, localStorageService, utils, $location, $mdUtil,
                                    $routeParams, $sce, $mdSidenav, $q, profileHandler, apiClient) {

    var dateId = 4;
    var getUrlPath = function () {
      return $routeParams.questionnaireId || 15;
    };


    $scope.setDate = function () {
      $scope.answers[dateId] = moment($scope.dates[dateId]).format('DD/MM/YYYY');
    };

    $scope.toggleLeft = buildToggler('left');
    $scope.toggleRight = buildToggler('right');
    /**
     * Build handler to open/close a SideNav; when animation finishes
     * report completion in console
     */
    function buildToggler(navID) {
      var debounceFn =  $mdUtil.debounce(function(){
        $mdSidenav(navID)
          .toggle()
          .then(function () {
            $rootScope.$broadcast('toggleOpen');
          });
      },300);
      return debounceFn;
    }

    $scope.setProfile = function (profile) {
      profileHandler.setProfile(profile);
    };


    var init = function () {
      $scope.selected = [];
      $scope.query = {
        filter: '',
        order: 'id',
        limit: 20,
        page: 1
      };

      // in the future we may see a few built in alternate headers but in the mean time
      // you can implement your own search header and do something like
      $scope.search = function (predicate) {
        $scope.filter = predicate;
      };

      $scope.onOrderChange = function (order) {
        var d = $q.defer();
        d.resolve(json);
        return d.promise;
      };

      $scope.onPaginationChange = function (page, limit) {
        var d = $q.defer();
        var j = json.splice(0, limit);
        d.resolve(j);
        return d.promise;
      };

      apiClient.getUsers({id:15}).then(function (users) {
        angular.forEach(users.items, function (item) {
          angular.forEach(item, function (itm, key) {
            var i = null;
            try {
              if (key === '5' || key === '39') {
                i = JSON.parse(itm[0]);
                itm[0] = i;
              }
            } catch (e) {}
          });
        });
        $scope.persons = users.items;
      })
    };

    $scope.profile = function (id) {
      $location.url('/profile/' + id);
    };


    init();

  });


json = [
  {
    "id": 41,
    "status": "1st Interview",
    "firstName": "First Name 41",
    "familyName": "Family Name 41",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 86,
    "status": "1st Interview",
    "firstName": "First Name 86",
    "familyName": "Family Name 86",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 77,
    "status": "1st Interview",
    "firstName": "First Name 77",
    "familyName": "Family Name 77",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 32,
    "status": "1st Interview",
    "firstName": "First Name 32",
    "familyName": "Family Name 32",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 23,
    "status": "1st Interview",
    "firstName": "First Name 23",
    "familyName": "Family Name 23",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 68,
    "status": "1st Interview",
    "firstName": "First Name 68",
    "familyName": "Family Name 68",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 59,
    "status": "1st Interview",
    "firstName": "First Name 59",
    "familyName": "Family Name 59",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 14,
    "status": "1st Interview",
    "firstName": "First Name 14",
    "familyName": "Family Name 14",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 95,
    "status": "1st Interview",
    "firstName": "First Name 95",
    "familyName": "Family Name 95",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 50,
    "status": "1st Interview",
    "firstName": "First Name 50",
    "familyName": "Family Name 50",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 5,
    "status": "1st Interview",
    "firstName": "First Name 5",
    "familyName": "Family Name 5",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 51,
    "status": "2nd Interview",
    "firstName": "First Name 51",
    "familyName": "Family Name 51",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 6,
    "status": "2nd Interview",
    "firstName": "First Name 6",
    "familyName": "Family Name 6",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 96,
    "status": "2nd Interview",
    "firstName": "First Name 96",
    "familyName": "Family Name 96",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 87,
    "status": "2nd Interview",
    "firstName": "First Name 87",
    "familyName": "Family Name 87",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 42,
    "status": "2nd Interview",
    "firstName": "First Name 42",
    "familyName": "Family Name 42",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 78,
    "status": "2nd Interview",
    "firstName": "First Name 78",
    "familyName": "Family Name 78",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 33,
    "status": "2nd Interview",
    "firstName": "First Name 33",
    "familyName": "Family Name 33",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 69,
    "status": "2nd Interview",
    "firstName": "First Name 69",
    "familyName": "Family Name 69",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 24,
    "status": "2nd Interview",
    "firstName": "First Name 24",
    "familyName": "Family Name 24",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 15,
    "status": "2nd Interview",
    "firstName": "First Name 15",
    "familyName": "Family Name 15",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Audit",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 60,
    "status": "2nd Interview",
    "firstName": "First Name 60",
    "familyName": "Family Name 60",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 71,
    "status": "EP Process",
    "firstName": "First Name 71",
    "familyName": "Family Name 71",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Audit",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 26,
    "status": "EP Process",
    "firstName": "First Name 26",
    "familyName": "Family Name 26",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 62,
    "status": "EP Process",
    "firstName": "First Name 62",
    "familyName": "Family Name 62",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 17,
    "status": "EP Process",
    "firstName": "First Name 17",
    "familyName": "Family Name 17",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 98,
    "status": "EP Process",
    "firstName": "First Name 98",
    "familyName": "Family Name 98",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 53,
    "status": "EP Process",
    "firstName": "First Name 53",
    "familyName": "Family Name 53",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 8,
    "status": "EP Process",
    "firstName": "First Name 8",
    "familyName": "Family Name 8",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 89,
    "status": "EP Process",
    "firstName": "First Name 89",
    "familyName": "Family Name 89",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 44,
    "status": "EP Process",
    "firstName": "First Name 44",
    "familyName": "Family Name 44",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 35,
    "status": "EP Process",
    "firstName": "First Name 35",
    "familyName": "Family Name 35",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 80,
    "status": "EP Process",
    "firstName": "First Name 80",
    "familyName": "Family Name 80",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 66,
    "status": "Hold",
    "firstName": "First Name 66",
    "familyName": "Family Name 66",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 21,
    "status": "Hold",
    "firstName": "First Name 21",
    "familyName": "Family Name 21",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 57,
    "status": "Hold",
    "firstName": "First Name 57",
    "familyName": "Family Name 57",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Audit",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 12,
    "status": "Hold",
    "firstName": "First Name 12",
    "familyName": "Family Name 12",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 3,
    "status": "Hold",
    "firstName": "First Name 3",
    "familyName": "Family Name 3",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 93,
    "status": "Hold",
    "firstName": "First Name 93",
    "familyName": "Family Name 93",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 48,
    "status": "Hold",
    "firstName": "First Name 48",
    "familyName": "Family Name 48",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 39,
    "status": "Hold",
    "firstName": "First Name 39",
    "familyName": "Family Name 39",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 84,
    "status": "Hold",
    "firstName": "First Name 84",
    "familyName": "Family Name 84",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 75,
    "status": "Hold",
    "firstName": "First Name 75",
    "familyName": "Family Name 75",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 30,
    "status": "Hold",
    "firstName": "First Name 30",
    "familyName": "Family Name 30",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 1,
    "status": "New",
    "firstName": "First Name 1",
    "familyName": "Family Name 1",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Audit",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 91,
    "status": "New",
    "firstName": "First Name 91",
    "familyName": "Family Name 91",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 46,
    "status": "New",
    "firstName": "First Name 46",
    "familyName": "Family Name 46",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 82,
    "status": "New",
    "firstName": "First Name 82",
    "familyName": "Family Name 82",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 37,
    "status": "New",
    "firstName": "First Name 37",
    "familyName": "Family Name 37",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 73,
    "status": "New",
    "firstName": "First Name 73",
    "familyName": "Family Name 73",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 28,
    "status": "New",
    "firstName": "First Name 28",
    "familyName": "Family Name 28",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 19,
    "status": "New",
    "firstName": "First Name 19",
    "familyName": "Family Name 19",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 64,
    "status": "New",
    "firstName": "First Name 64",
    "familyName": "Family Name 64",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 55,
    "status": "New",
    "firstName": "First Name 55",
    "familyName": "Family Name 55",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 10,
    "status": "New",
    "firstName": "First Name 10",
    "familyName": "Family Name 10",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 100,
    "status": "New",
    "firstName": "First Name 100",
    "familyName": "Family Name 100",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 61,
    "status": "Offer",
    "firstName": "First Name 61",
    "familyName": "Family Name 61",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 16,
    "status": "Offer",
    "firstName": "First Name 16",
    "familyName": "Family Name 16",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 7,
    "status": "Offer",
    "firstName": "First Name 7",
    "familyName": "Family Name 7",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 97,
    "status": "Offer",
    "firstName": "First Name 97",
    "familyName": "Family Name 97",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 52,
    "status": "Offer",
    "firstName": "First Name 52",
    "familyName": "Family Name 52",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 43,
    "status": "Offer",
    "firstName": "First Name 43",
    "familyName": "Family Name 43",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Audit",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 88,
    "status": "Offer",
    "firstName": "First Name 88",
    "familyName": "Family Name 88",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 79,
    "status": "Offer",
    "firstName": "First Name 79",
    "familyName": "Family Name 79",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 34,
    "status": "Offer",
    "firstName": "First Name 34",
    "familyName": "Family Name 34",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 70,
    "status": "Offer",
    "firstName": "First Name 70",
    "familyName": "Family Name 70",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 25,
    "status": "Offer",
    "firstName": "First Name 25",
    "familyName": "Family Name 25",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 81,
    "status": "Placed",
    "firstName": "First Name 81",
    "familyName": "Family Name 81",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 36,
    "status": "Placed",
    "firstName": "First Name 36",
    "familyName": "Family Name 36",
    "ourRating": 1,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 27,
    "status": "Placed",
    "firstName": "First Name 27",
    "familyName": "Family Name 27",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 72,
    "status": "Placed",
    "firstName": "First Name 72",
    "familyName": "Family Name 72",
    "ourRating": 2,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 63,
    "status": "Placed",
    "firstName": "First Name 63",
    "familyName": "Family Name 63",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 18,
    "status": "Placed",
    "firstName": "First Name 18",
    "familyName": "Family Name 18",
    "ourRating": 3,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 99,
    "status": "Placed",
    "firstName": "First Name 99",
    "familyName": "Family Name 99",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 54,
    "status": "Placed",
    "firstName": "First Name 54",
    "familyName": "Family Name 54",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 9,
    "status": "Placed",
    "firstName": "First Name 9",
    "familyName": "Family Name 9",
    "ourRating": 4,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 90,
    "status": "Placed",
    "firstName": "First Name 90",
    "familyName": "Family Name 90",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Other",
    "primaryClients": "Financial Services"
  },
  {
    "id": 45,
    "status": "Placed",
    "firstName": "First Name 45",
    "familyName": "Family Name 45",
    "ourRating": 5,
    "articleship": "SME Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "More than two",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Other",
    "primaryClients": "Industry "
  },
  {
    "id": 11,
    "status": "Rejected",
    "firstName": "First Name 11",
    "familyName": "Family Name 11",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 56,
    "status": "Rejected",
    "firstName": "First Name 56",
    "familyName": "Family Name 56",
    "ourRating": 1,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 47,
    "status": "Rejected",
    "firstName": "First Name 47",
    "familyName": "Family Name 47",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 92,
    "status": "Rejected",
    "firstName": "First Name 92",
    "familyName": "Family Name 92",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 2,
    "status": "Rejected",
    "firstName": "First Name 2",
    "familyName": "Family Name 2",
    "ourRating": 2,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2013,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 83,
    "status": "Rejected",
    "firstName": "First Name 83",
    "familyName": "Family Name 83",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 38,
    "status": "Rejected",
    "firstName": "First Name 38",
    "familyName": "Family Name 38",
    "ourRating": 3,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 29,
    "status": "Rejected",
    "firstName": "First Name 29",
    "familyName": "Family Name 29",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Audit",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 74,
    "status": "Rejected",
    "firstName": "First Name 74",
    "familyName": "Family Name 74",
    "ourRating": 4,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 65,
    "status": "Rejected",
    "firstName": "First Name 65",
    "familyName": "Family Name 65",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 25%",
    "primaryClients": "Industry "
  },
  {
    "id": 20,
    "status": "Rejected",
    "firstName": "First Name 20",
    "familyName": "Family Name 20",
    "ourRating": 5,
    "articleship": "Large Firm",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "2nd Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 25%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 31,
    "status": "Sonru",
    "firstName": "First Name 31",
    "familyName": "Family Name 31",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 76,
    "status": "Sonru",
    "firstName": "First Name 76",
    "familyName": "Family Name 76",
    "ourRating": 1,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2014,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 67,
    "status": "Sonru",
    "firstName": "First Name 67",
    "familyName": "Family Name 67",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "70-79",
    "educationDegree": "70-79",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 22,
    "status": "Sonru",
    "firstName": "First Name 22",
    "familyName": "Family Name 22",
    "ourRating": 2,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2013,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 13,
    "status": "Sonru",
    "firstName": "First Name 13",
    "familyName": "Family Name 13",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 58,
    "status": "Sonru",
    "firstName": "First Name 58",
    "familyName": "Family Name 58",
    "ourRating": 3,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2015,
    "department": "Technical Accounting",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 94,
    "status": "Sonru",
    "firstName": "First Name 94",
    "familyName": "Family Name 94",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "80-89",
    "educationDegree": "80-89",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 49,
    "status": "Sonru",
    "firstName": "First Name 49",
    "familyName": "Family Name 49",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 4,
    "status": "Sonru",
    "firstName": "First Name 4",
    "familyName": "Family Name 4",
    "ourRating": 4,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2012,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  },
  {
    "id": 85,
    "status": "Sonru",
    "firstName": "First Name 85",
    "familyName": "Family Name 85",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Audit",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "90-100",
    "educationDegree": "90-100",
    "performanceRating": "Top 10%",
    "primaryClients": "Industry "
  },
  {
    "id": 40,
    "status": "Sonru",
    "firstName": "First Name 40",
    "familyName": "Family Name 40",
    "ourRating": 5,
    "articleship": "Big 4",
    "accountancyQualificationYearQualify": 2011,
    "department": "Other",
    "accountancyQualificationAttempts": "1st Time",
    "educationHighschool": "Below 70",
    "educationDegree": "Below 70",
    "performanceRating": "Top 10%",
    "primaryClients": "Financial Services"
  }
];